language: node_js

node_js:
  - '12.13.0'

branches:
  only:
    - master

install: npm install

script:
  - npm run build
  - npm run test

notifications:
  email:
    recipients:
      - 'bbonggu92@gmail.com'
